name: build iso

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build buildenv -t bill-buildenv

    - name: Build
      run: |
        docker run --rm -v "$(pwd):/root/env" bill-buildenv make build-x86_64
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
          name: "BILL-nightly"
          path: "dist/"
